### ISSUE TITLE
Innovator's Toolkit R1

### ISSUE THREAD

**Issue by ccoldwell** [bcgov/digital-toolkit#19]
Value: $9,000.00Closes: Thursday, February 8, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p class="MsoNormal">As the Government of British Columbia increases delivery of digital services, there is a need to help all stakeholders understand what &ldquo;digital&rdquo; means.&nbsp;&nbsp; At the same time, there is a subset of stakeholders that will need to know what tools, techniques, and methodologies are recommended for their use to design and build digital services.&nbsp; The website described by the GitHub repositories in the next paragraph is a first iteration, a prototype, of a &ldquo;Digital Guide&rdquo; for the Government of British Columbia.</p>
<p class="MsoNormal">Beginning a journey towards a &ldquo;BC Digital Guide,&rdquo; this site is the first step.&nbsp; Modelled after <a href="https://18f.gsa.gov/">18F</a> in the U.S. and <a href="https://www.gov.uk/government/organisations/government-digital-service">UK Government Digital Service</a>, the government reference <a href="https://github.com/bcgov/innovation-toolkit">in this repository</a>, supported by the guides found through <a href="https://github.com/bcgov/guide-of-guides">this repository </a>&nbsp;is organized like this (from the FAQ):&nbsp; &ldquo;You&rsquo;ll find three layers to the toolkit: (i) a front page describing basic steps and principles, (ii), a set of high level guides that further define those steps and principles, and (iii) detailed guides providing a deeper level of information and instruction with those responsible for designing and delivering simple, streamlined, modern services.&rdquo;&nbsp;</p>
<p>This iteration intends to build out content, to fill in the blanks, as it were, to take the collection of guides to a first official release.&nbsp; Most of this work is focused on updating the detailed guides, adding new guides, and providing links to other good related government references.<ins cite="mailto:Rabb,%20R.%20Jim" datetime="2018-01-30T16:38"> </ins></p>
<p class="MsoNormal">Phase 1</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Propose a methodology or mechanism to facilitate contribution from anyone across government</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Propose a method of measuring, collecting, and analysing visitor behaviour so that the content, navigation, and overall service can be improved.</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Implement both of these methods.</p>
<p class="MsoNormal">Phase 2</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Fix navigation so that it works as expected, forward and back.</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Provide a Search function on the home page so that content on that page is easier to find.</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Correct feedback and email links to proper endpoints (to be provided.)</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Include new and updated content (to be provided.)</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Include a section for &ldquo;Corporate Enablers&rdquo;, and a one-page description of what each is, and how to consume them (content to be provided).</p>
<p class="MsoNormal" style="margin-left: 1.0cm;">Include an expanded collection of links for DataBC (links to be provided).</p><h2>Acceptance Criteria</h2><ul type="disc">
<li class="MsoNormal" style="line-height: normal; vertical-align: baseline;">Work with our Agile/Scrum team (4000 Seymour Place in Victoria, BC):</li>
<ul type="circle">
<li class="MsoNormal" style="line-height: normal; vertical-align: baseline;">The DigitalToolkit team works in 1-week sprints. You will attend in-person planning (2 hours) and review (3 hours) meetings for each sprint.</li>
<li class="MsoNormal" style="line-height: normal; vertical-align: baseline;">You will track your work with the team on our DigitalToolkit Trello board</li>
</ul>
<li class="MsoNormal" style="line-height: normal; vertical-align: baseline;">Completion of Phase 1&nbsp; $4,000</li>
<li class="MsoNormal" style="line-height: normal; vertical-align: baseline;">Completion of Phase 2&nbsp; $5,000</li>
</ul><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-innovator-s-toolkit-r1">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, February 8, 2018</b>.</p><p>We plan to assign this opportunity by <b>Saturday, February 10, 2018</b> with work to start on <b>Wednesday, February 14, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><ol start="1" type="1">
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: EN-CA;">Your confirmation of being able to commit the time to meet all of the Acceptance Criteria by<strong>&nbsp;Wednesday, February 7,</strong>&nbsp;<strong>2018</strong>.</span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: EN-CA;">A short (200 words or less) summary of your experience working with agile projects (40 points).</span></li>
<li class="MsoNormal" style="mso-margin-top-alt: auto; mso-margin-bottom-alt: auto; line-height: normal; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;"><span style="font-size: 12.0pt; font-family: 'Times New Roman','serif'; mso-fareast-font-family: 'Times New Roman'; mso-fareast-language: EN-CA;">References to your relevant experience and demonstrated ability to do the work (60 points). For example, a link to your GitHub projects</span></li>
</ol>

**Comment by RobertGoesByJim** [comment]
For questions and clarification, please contact Jim Rabb at jim.rabb@gov.bc.ca .

**Comment by RobertGoesByJim** [comment]
Friendly reminder, that this opportunity closes in a little over three hours.  Please submit your proposals prior to close.  Thanks for your interest.

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by RobertGoesByJim** [comment]
Thank you for your interest, and the time invested in the proposals.  This opportunity is awarded to jonathanbell - we're looking forward to Go!

**Comment by jonathanbell** [comment]
Thank you all for the opportunity: @RobertGoesByJim @jackieredmond
