### ISSUE TITLE
Application Not Available

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/digital-toolkit#22]
![application-not-available](https://user-images.githubusercontent.com/29607430/37167494-ede2161a-22b6-11e8-8650-b19aba6eebb3.jpeg)

Trying to view the guide, the link in the description leads to this page.

**Comment by RobertGoesByJim** [comment]
thanks @dlevineBC .  we'll get on this.  looks like we still have an old reference...

**Comment by RobertGoesByJim** [comment]
link updated @dlevineBC

**Comment by jonathanbell** [comment]
Please use the new URL: https://digital-toolkit.pathfinder.gov.bc.ca/
