### ISSUE TITLE
Webserver to serve static content

### ISSUE THREAD

**Issue by agehlers** [bcgov/digital-toolkit#24]
The application currently uses ruby-webrick (https://github.com/ruby/webrick) which intended for low-traffic non production sites.
Suggest to research of other webservers (caddy, ruby-unicorn, ruby-thin, etc) which are more appropriate for a production site.

**Comment by jonathanbell** [comment]
Added to our Trello board.

**Comment by RobertGoesByJim** [comment]
Shelly made the change to serve with caddy
